source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

#We'll add this back in later
inhibit_all_warnings!
#use_frameworks!

target :"shortList" do

#Foundation Helpers
pod 'BlocksKit', '2.2.5'
pod 'Parse'
pod 'ParseFacebookUtils'
pod 'ParseTwitterUtils'

#Model
pod 'Mantle'

#Networking
pod 'AFNetworking'
pod 'SDWebImage'

#UI
pod 'ParseUI'
pod 'MBProgressHUD'
pod 'CRToast'

#Analytics/Crash
pod "HockeySDK", :subspecs => ['CrashOnlyLib']
pod 'Flurry-iOS-SDK/FlurrySDK'

end

target :"shortListTests" do
pod 'Mantle'
end
