source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

#We'll add this back in later
inhibit_all_warnings!


#Foundation Helpers
pod 'BlocksKit', '2.2.5'
pod 'Parse'

#Model
pod 'Mantle'
pod 'QBValidator'

#Networking
pod 'AFNetworking'
pod 'SDWebImage'

#UI
pod 'ParseUI'
pod 'MBProgressHUD', '~> 0.9'

target :"shortListTests", :exclusive => true do
pod 'Mantle'
end
